# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a45569aef8ba159c1aa8ac8b97d9199b165f33bf0f608ed17feddfca76b948786ca2564ab64daec48872a966c075ca470cbf08ae1c362791689d09fdeef8c4

test:
  secret_key_base: 215fdae92dcddedc5bddeba0210d6b6b488f7cba5c912eb8aea0c43cf49a85711cab6a1cf8649640f0225eb0d3c647f8d0a95d742a686dff6f38e887ac7cbb6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
